### ISSUE TITLE
Question: How to use the firestore listener ?

### ISSUE THREAD

**Issue by gdo** [jeffbski/redux-logic#107]
Hello,

I use redux-logic for my site and it work very well but I don't understand how to combine redux-logic and  firestore listener.

an example :
`
export const display = createLogic({
  type: [AUTH_USER],

  process({ getState }, dispatch, done) {
    const state = getState()
    const userID = authSelectors.userID(state)

      if (!unsubscribeFirebase) {
        const db = firebase.firestore()
        unsubscribeFirebase = db.collection('botReducer').doc(userID)
                                .onSnapshot((doc) => {
                                  const agentState = doc.data()
 
                                  dispatch(setState(agentState))
                                  dispatch(initialize())
                                  done()
                                })
       } else {
          done()
       }
  },
})
`
The first time setState is seen by my reducer but not the second time. I think it' s normal because I want to call done() twice. 
I think I could use store.dispatch(...) but it's not very elegant.

Do you have a better solution?

Best regards

**Comment by jeffbski** [comment]
Since this logic will be responding to many updates then you don't want to call done (unless you are completely finished listening).

So your callback in onSnapshot will be called every time the botReducer collection updates. Thus just omit calling done in your logic and you'll continue to get updates.

You can set processOptions.warnTimeout to 0 so it doesn't complain about your logic staying open in the console in development mode.

**Comment by gdo** [comment]
Thanks, it's work very well.
