### ISSUE TITLE
Firebase database automatic refresh dispatch not working on React Native

### ISSUE THREAD

**Issue by MrRoyce** [jeffbski/redux-logic#11]
Hi there, 
I'm building a test app with RN that uses the redux-logic library.  I have several pieces working, but I recently ran into an issue that I can't resolve.

I'm using the firebase database 'on' event, that will automatically trigger whenever the backend database is changed.  For example, I have a db of users, and if I add a new user the event is triggered, which does a dispatch to update my redux store.

Here is the docs on the FB call:

https://firebase.google.com/docs/database/web/read-and-write

Here is the code snippet for my logic:

```javascript
export const employeesFetchLogic = createLogic({
  type: EMPLOYEES_FETCH_REQUEST,
  latest: false, // take latest only

  // firebase injected
  // from configureStore logic deps
  process({ firebase }, dispatch) {
    const { currentUser } = firebase.auth();

    //  Get all the employees from firebase
    firebase.database().ref(`/users/${currentUser.uid}/employees`)
      .on('value', snapshot => {
        // THIS DISPATCH ONLY WORKS THE 1ST TIME!
        dispatch({ type: EMPLOYEES_FETCH_SUCCESS, payload: snapshot.val() });
      })
    ;
  }
});
```

It works fine the 1st time its called after I add a new record when the app 1st loads, but the dispatch is not passed through to my reducer the second or subsequent times.  I stepped through the debugger and can see the event being triggered every time and the reducer being called the 1st time, but the dispatch is not passed through to the reducer after the 1st time.

Any ideas why this could be?

regards,
Royce

**Comment by jeffbski** [comment]
Since you are wanting to do multiple dispatch there are a few ways to handle it (by default redux-logic is assuming single dispatch). 

It is explained in the advanced section [here](https://github.com/jeffbski/redux-logic/blob/master/docs/api.md#dispatch---multi-dispatching-and-optional-second-argument-options)

The easiest thing to do is to add the second argument to the dispatch function to enable multiple dispatches. 

```js
export const employeesFetchLogic = createLogic({
  type: EMPLOYEES_FETCH_REQUEST,
  latest: false, // take latest only

  // firebase injected
  // from configureStore logic deps
  process({ firebase }, dispatch) {
    const { currentUser } = firebase.auth();

    //  Get all the employees from firebase
    firebase.database().ref(`/users/${currentUser.uid}/employees`)
      .on('value', snapshot => {
        dispatch({ type: EMPLOYEES_FETCH_SUCCESS, payload: snapshot.val() },
                 { allowMore: true }); // allow multiple dispatching
      })
    ;
  }
});
```

Once you are done dispatching you can follow up with an empty `dispatch()` to tell redux-logic that you are completely done, but in your case it sounds like you want it to continue indefinitely so the above code should enable that.

**Comment by MrRoyce** [comment]
Amazing, thanks for the quick and complete response.

It works perfectly.  I love using this library and Iearn more about it every day.

**Comment by jeffbski** [comment]
Fantastic! You are quite welcome. It really simplifies my code too, so I am glad to be able to share it with you and others. Have a great day!

**Comment by MrRoyce** [comment]
Not sure if you saw my last question?

Why isn't the 'allowMore' default set to true? Is there any downside to that?

**Comment by jeffbski** [comment]
Sorry, I missed that when reading. I guess I need to slow down. :-)

Well I guess that it is primarily that way since I was thinking that most use cases would be single dispatch and I didn't want most people to have to indicate when they were done. Basically I needed to know when I can close out the underlying observable. In the case of a subscription you probably want to keep it open indefinitely (or at least till you tell it to cancel). There's nothing wrong with keeping the observable open. If you would possibly have additional triggers of EMPLOYEE_FETCH_REQUEST then you could add this to your code so the old observables will be closed and firebase can cancel old requests. 

```js
export const employeesFetchLogic = createLogic({
  type: EMPLOYEES_FETCH_REQUEST,
  latest: false, // take latest only

  // firebase injected
  // from configureStore logic deps
  process({ firebase, cancelled$ }, dispatch) {
    const { currentUser } = firebase.auth();

    //  Get all the employees from firebase
   const onData = snapshot => {
     dispatch({ type: EMPLOYEES_FETCH_SUCCESS, payload: snapshot.val() },
              { allowMore: true }); // allow multiple dispatching
   });

    firebase.database().ref(`/users/${currentUser.uid}/employees`)
      .on('value', onData);

    // we can listen to cancelled$ to know if we need to cleanup
    // this can get fired for a take latest or a cancelAction
    cancelled$.subscribe({ next: () => { 
      // perform any cancellation cleanup
      // tell firebase we no longer need data for this cb
      firebase.database().ref(`/users/${currentUser.uid}/employees`).off(onData);
      dispatch(); // empty dispatch to tell redux-logic we are done      
    }});
  }
});
```


This just lets things be closed if a newer request comes in or if you had a cancel action defined and wanted to invoke that to stop updates. 

redux-logic will automatically prevent the additional dispatching from occurring once the new request was triggered by having the `latest: false` but it doesn't prevent firebase from sending the data multiple times unless you were to tell it you are done. So it would send the data and then redux-logic would ignore it if it isn't the latest request. Thus it's best to go ahead and cleanup as well when you are done.

So the best answer is to go ahead and add the cleanup like I indicate above that way, firebase will be told when you no longer need data and also you can tell redux-logic you are done. I think technically you wouldn't need to do the empty dispatch in the case of things being cancelled (for take latest or cancel action) since the observable is closed anyway after being cancelled.

So really in this case where you will want a long running subscription, you could leave out the dispatch() but you would probably want to go ahead and tell fb you are done just to save it sending things.

I hope that starts to explain it. It's a rough edge that I'd like to clean up but haven't quite figured out the best approach.

**Comment by jeffbski** [comment]
I had a typo in the above which I corrected, I meant if you have `latest: true` then it will cancel old requests if a new one comes in. 

So if you set `latest: true` then if somehow another  EMPLOYEES_FETCH_REQUEST action comes in, then the old observable will be cancelled. The same would be true if you set the `cancel: EMPLOYEES_FETCH_CANCEL` property.

Otherwise if multiple actions EMPLOYEES_FETCH_REQUEST come in without take latest turned on then you'll have multiple subscriptions firing. 

Depending on how you have coded your app that might not be a possible situation, but if there is ever a doubt it is good to simply just turn on the `latest: true` and it will cancel the old logic.

If EMPLOYEES_FETCH_REQUEST is only ever going to be fired one time and you never need to cancel then you can ignore all of this about cancellation and take latest since you just won't run into it. In that case you can safely leave the initial observable open and subscribed. 

However you might want to consider having some cancel action(s) in case you navigate to a different page or something, you might actually want to cancel the data from coming.

**Comment by jeffbski** [comment]
@MrRoyce did I just confuse you worse? or are we good to close this issue? Just wanted to check. Thanks.

**Comment by MrRoyce** [comment]
Everything is working great. I can't imagine writing asynchronous logic with out this library. I'm using it for a react-native app now. Thanks again for your help.

I'll close this issue.

**Comment by jeffbski** [comment]
Fantastic!

Also let me know if #10 is still a problem for you. Thanks!!

**Comment by MrRoyce** [comment]
Yes, unfortunately, #10 still gives the error during the production build.  The production app still works, but it will throw the error if the console is open for the page. I haven't been able to make any headway on it.  I'm hoping that when WebPack v2 goes stable and I conver to that release, that it will be fixed, although like I mentioned before, I'm not sure if it is a WebPack issue??

**Comment by jeffbski** [comment]
ok, thanks for the update.
