### ISSUE TITLE
[0.15.3] Typescript Error: Undefined does not meet it's constraint 'object'

### ISSUE THREAD

**Issue by chmaltsp** [jeffbski/redux-logic#115]
Hello

Thanks for getting the typescript typings in. Maybe I am doing something wrong, but when using 2.9.2 you cannot extend an object and set the default to `undefined`
![screen shot 2018-08-07 at 10 50 22 am](https://user-images.githubusercontent.com/10981965/43783434-ba6b966c-9a2f-11e8-9093-6422dfd74cf6.png)

Setting changing the definition to 
```
export type ArgumentAction<
  Type extends string = string,
  Payload extends object = {},
  Meta extends object = {}
> = ActionBasis<Type> & Partial<Action<string, object, object>>;
```

helps but then `action.payload` ends up being undefined in `createLogic({ process({ action }})`. I'm still kind of new to TS but this prevents the project form building! @alvis maybe you know more about this?

**Comment by alvis** [comment]
@chmaltsp Thanks for reporting. I apologise as I forgot this syntax will cause a problem with "strictNullChecks". The reason of using the 'undefined' type is to take the advantage of the news conditional type, so that for example if the payload is set to 'undefined', the resulting action object would not have a payload field.

I'm working on a fix on it and would make a PR soon.

**Comment by alvis** [comment]
@chmaltsp #117 should now resolve the problem.

Also thanks for pointing out the recommended types for `payload` and `meta` too. I'm working on it.

**Comment by gustavopch** [comment]
> @chmaltsp #117 should now resolve the problem.
> 
> Also thanks for pointing out the recommended types for `payload` and `meta` too. I'm working on it.

@alvis @jeffbski  As the comment above, typings for `payload` and `meta` should extend `any`, but they still extend `object | undefined`.
