### ISSUE TITLE
Crash: "Invariant violation: Objects are not valid as a React child"

### ISSUE THREAD

**Issue by cgerikj** [jeffbski/redux-logic#138]
Hi!

I'm getting a very strange error when running my app in prod on Android (it also happens when I disable dev mode):
Invariant Violation: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner})

What causes the error is this line:
const logicMiddleware = createLogicMiddleware();

Even if I don't use the middleware it crashes. Even after removing my logics array and creating it without parameters it crashes. Do you have any idea what causes this? It makes zero sense to me!

This is after updating to 2.0.3 from 0.12.3. I had to update because of another issue.
react-native version 0.54.2

**Comment by sanbornhilland** [comment]
@cgerikj That's a [React error](https://stackoverflow.com/questions/33117449/invariant-violation-objects-are-not-valid-as-a-react-child) so it sounds like the issue is not a `redux-logic` issue but is instead somewhere in your React code. Without having more information it sounds like that line is perhaps just uncovering a bug that exists elsewhere. Maybe your logic is causing some data to be set incorrectly in your Redux store and you're accidentally trying to render it. I'd suggest trying to find out what line is throwing that error and double check what you're rendering there.

BTW, `invariants` should not actually throw in production so you might want to double check you have you environment set correctly when building your app. There's more information about how they are intended to work:

https://github.com/zertosh/invariant
https://github.com/4Catalyzer/babel-plugin-dev-expression

**Comment by cgerikj** [comment]
Hi, thanks for replying! I know it's a react error. It's crashing with an empty logics array so it shouldn't be doing anything and I have even tried to render nothing but an empty View.. :(

**Comment by sanbornhilland** [comment]
@cgerikj I see. It's hard to diagnosis it without further access to the code that is failing. Have you been able to track down exactly where the error is thrown?

**Comment by cgerikj** [comment]
@sanbornhilland I will try to track it down in January and let you know if i find it! :)

**Comment by henninghall** [comment]
I manage to reproduce the bug by:
1. `react-native init --version 0.54.2`
2. `yarn add redux-logic@2.0.3`
3. Adding `import { createLogic } from 'redux-logic'` in App.js

**Comment by henninghall** [comment]
Im not sure why but when removing all rows of `require("core-js/modules/es6.symbol");` in the build files it seems to work. 

It also works by running the source files instead of the build files by changing `"main": "build-lib/index.js"` to `"main": "src/index.js"` in package.json

**Comment by elijamesedric** [comment]
I was having this error and it turned out to be that I was unintentionally including an Object in my JSX code that I had expected to be a string value:

return (
<BreadcrumbItem href={routeString}>
{breadcrumbElement}
</BreadcrumbItem>
)
breadcrumbElement used to be a string but due to a refactor had become an Object. Unfortunately, React’s error message didn’t do a good job in pointing me to the line where the problem existed. I had to follow my stack trace all the way back up until I recognized the “props” being passed into a component and then I found the offending code.

You’ll need to either reference a property of the object that is a string value or convert the Object to a string representation that is desirable. One option might be JSON.stringify if you actually want to see the contents of the Object

Full Source With example Visit [Here](https://icetutor.com/question/invariant-violation-objects-are-not-valid-as-a-react-child/)
