### ISSUE TITLE
Duplicate success process options calls due to options request?

### ISSUE THREAD

**Issue by shauntrennery** [jeffbski/redux-logic#17]
I've noticed a weird bug in an application using redux-logic. I'm using axios to post to a third party API. Using developer tools, the request shows up twice under the network tab. Options and the final post. 

I suspect the success process options is triggering twice as a result of the options request.

I'm having a difficult time replicating the issue using the reqres.in service thou.

Is this a possibility or could it be related to another bug deeper in my code base.

Many thanks.

**Comment by shauntrennery** [comment]
Does not appear to be the case. I've removed the options call from axios by setting the Content-Type to application/x-www-form-urlencoded. The duplicate success process type is still occurring.

**Comment by jeffbski** [comment]
I suspect that this is occurring from Axios (it shouldn't have anything to do with redux-logic), but I believe this is part of a normal pre-flight for CORS requests. See the pre-flight section of https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Basically the http client makes an OPTIONS request before it does the POST so that it can verify some things from the server. There is more discussion about it here.

http://stackoverflow.com/questions/29954037/how-to-disable-options-request

So it's all related to browser security and what happens when making cross-site requests, it wouldn't occur when talking to the same site.
