### ISSUE TITLE
Question: Workflow

### ISSUE THREAD

**Issue by seanlindo** [jeffbski/redux-logic#39]
Do you find yourself creating constants in the following pattern?

`SEARCH_FILTERS_LOAD_REQUEST`

`SEARCH_FILTERS_LOAD_SUCCESS`

`SEARCH_FILTERS_LOAD_FAILURE`

The three constants above are associated with an asynchronous operation. 

`redux-logic` handles the first constant by making an asynchronous call (I use async/await). My reducer also handles the first constant by updating some "loading" state variable which controls various loading indicators in the UI. 

Upon success or failure, `redux-logic` dispatches one of the final two constants, which the reducer acts on (updating the search filters, setting the loading state to false, etc.), and perhaps dispatches an action to a toastr or modal store as well and then calls `done()`. 

Is this kind of three-pronged approach an anti-pattern?

**Comment by jeffbski** [comment]
Yes it is typical to want to respond to those three events distinctly so one would potentially have three constants for each request/response cycle.

Depending on what you are doing on failures, you might be able to get away with a more generic error event, but you are likely to have 2-3 for each async operation.

Redux, flux, event sourcing and event driven architectures all take a similar approach. Since those are all distinct events that occur over time and need different handlers, it makes sense to represent them individually. 

What would you suggest as an alternative?

As for the actual naming, many people use this upper snake case naming convention for constants, however I tend to lean towards a prefixed camel case form where the prefix is the domain or part of the app, so I might call these: 
 - search/filterLoad 
 - search/filterLoadSuccess 
 - search/filterLoadFailure

The prefix could be several levels deep if necessary.

**Comment by seanlindo** [comment]
Nothing to suggest as an alternative! Just was interested in a sanity check, that's all. The actual strings themselves are a prefixed camel case, and the exported identifiers take the form of the more recognizable uppercase variety. 

Thanks for responding!

**Comment by jeffbski** [comment]
It's always good to ask the question. It's when we think about the why carefully that we sometimes come up with other ideas. Have a great day!
