### ISSUE TITLE
processOptions not working but rxjs style does.

### ISSUE THREAD

**Issue by StevenTCramer** [jeffbski/redux-logic#40]
Jeff,

I am having a problem with a basic fetch using processOptions.  I tried to follow the example but it isn't working for me. Yet the rxjs style does.  Any help would be great.  I have included the gist below:

https://gist.github.com/StevenTCramer/7a09f1739f4dc17cc25e546bbbd62f89

I tried looking through the source to see if I could figure out my error, but I'm too much a newb to accomplish it tonight.

Thanks.

**Comment by jeffbski** [comment]
@StevenTCramer Thanks for reaching out. It looks like you just simply need to return the promise and everything should work. In some languages like Ruby, the last thing executed is returned, but in JS you still need to specifically return things.

```js
export const fetchLogic = createLogic({
  type: actionTypes.LOAD_INTIATION,
  cancelType: actionTypes.LOAD_CANCEL,
  latest: true, // take latest only
  processOptions: {
    successType: actionTypes.LOAD_SUCCESS,
    failType: actionTypes.LOAD_FAILURE
  },
  
  process({ httpClient }) {
    return httpClient.get(url) // return the promise that resolves with response.data
      .then(response => response.data);
  }
});
```

I also took out the processOptions.dispatchReturn since it defaults to true if you omit the dispatch/done in your process hook. So nothing wrong with having it there but just not needed.

**Comment by StevenTCramer** [comment]
Wow,  that was easy.  Thanks, Jeff!  The test case using your redux-logic-test passes now.

**Comment by jeffbski** [comment]
Fantastic! That's what I like to hear.
