### ISSUE TITLE
redux-logic: with no RxJs

### ISSUE THREAD

**Issue by SilentCicero** [jeffbski/redux-logic#48]
I love redux logic. Dude, this is great. I have a problem though... I'm addicted to making things very tiny. I know. It doesn't matter. I know size in the JS world is not really a problem. Most apps are just images anyway. But still. Before I go and do something stupid:

(1) if I built this LIB without RxJs/Observables what problems would I run into
(2) could I build a tiny faximily library and still handle things like (debouncing and throttling) without RxJS
(3) great work, I love this library.

**Comment by jeffbski** [comment]
@SilentCicero I know what you are saying. I like small as well. 

We take advantage of RxJS v5 ability to selectively import operators reducing the size but it still is about 12K (gzipped).

It might be possible to genericize this and allow the observable library to be swapped out but I haven't investigated that yet. I would have to find equivalent functionality in the alternative libs and make sure they behave similarly.

It is likely that observables will eventually become part of JavaScript (EcmaScript) and when that happens we'll be able to use the native observable which is likely to be based on RxJS and thus we won't need to include anything extra. It is anyone's guess about when that might happen, but there is quite a bit of interest in that happening (Jafar Hussain is leading that effort).

Debouncing and throttling are probably the easiest things to do and you can just steal that functionality from lodash (just pulling in those specific methods). 

The cancellation and dispatching the latest functionality are probably the more challenging features and observables do most of the heavy lifting for those.

So if you want to keep those features in your library then using some form of observables is ideal. It might be that the `most` or `baconjs` observable libraries would have what we need. I haven't investigated whether using `most` or `baconjs` would result in a smaller build or not. That would be the first thing to investigate otherwise if pulling in them results in the same size then no reason to go any further.

https://github.com/cujojs/most
https://baconjs.github.io/

I appreciate the kind words. If you decide to go forward with this effort, I'd love to keep up with your progress and I can help if you have any questions. If we can find equivalent functionality in a smaller lib and possibly make this swappable then I'd certainly consider doing this with redux-logic if it doesn't overly complicate the code. Whatever we do, I want to be ready for when JS gets native observables.

**Comment by SilentCicero** [comment]
```
function createLogic({
  type = undefined,
  validate = ({ action }, allow) => allow(action),
  transform = validate,
  process = (p, d, done) => done(),
  processOptions = {
    // string or action creator fn wrapping dispatched value
    successType: undefined, // default undefined
    // string or action creator fn wrapping dispatched, rejected, or thrown errors
    failType: undefined // default undefined
  },
  }) {
  return { type, validate, transform, process };
}

function createLogicMiddleware(logics, deps) {
  return ({ getState, dispatch }) => (next) => (action) => {
    // the types that require buisiness logic
    const stopTypes = logics.map(logic => logic.type);

    // if the action requires logic, stop and do logic, otherwise next..
    if (action.type.indexOf(stopTypes) !== -1) {

      // go through available logic
      logics.forEach(logic => {
        if (action.type === logic.type) {
          const done = () => {};
          const reject = () => {};
          const fail = error => dispatch({ type: logic.processOptions.failType, error });
          const success = value => dispatch({ type: logic.processOptions.successType, value });
          const processNext = (action) => {
            next(action);

            try {
              (logic.process({ getState, action, ...deps }, dispatch, done) || Promise.resolve(true))
                .then(success)
                .catch(fail);
            } catch (error) {
              fail(error);
            }
          };
          const validationArgs = [{ getState, action }, processNext, reject];

          logic.validate(...validationArgs);
          logic.transform(...validationArgs);
        }
      });
    } else {
      next(action);
    }
  };
}
```

Ball parking based on the things I need. Have not tested this yet.

**Comment by jeffbski** [comment]
If you are just using this subset of functionality then yes, you can certainly get away without pulling in observables.

**Comment by SilentCicero** [comment]
@jeffbski for sure, this code above works out of the box. It doesn't do everything, but it organized the logic with a similar API. I'll keep making updates in this thread.

**Comment by jeffbski** [comment]
Sounds like a plan. If it does what you need then you are golden.

**Comment by jeffbski** [comment]
I'll go ahead and close this since there is nothing outstanding to deal with, we can still use this to document any new findings.

**Comment by jeffbski** [comment]
That looks fine to me. I should update the README since the 12K is referring to redux-logic minified and gzipped. rxjs is separate but we only use select operators to keep the size down.

**Comment by cherniavskii** [comment]
What do you mean by select operators?

**Comment by jeffbski** [comment]
Out of rxjs, we only import operators that we use rather than the whole rxjs package. In the rxjs site, this is called creating a custom build where you are only including what you need. 

So redux-logic only imports operators it needs like
```js
import 'rxjs/add/observable/merge';
import 'rxjs/add/operator/debounceTime';
```

rather than `import rxjs from 'rxjs' which would pull in the entire package.

Thus if redux-logic is the only one using rxjs in your app then by using this technique the size included will be smaller than the full rxjs. Obviously if you import additional methods or the full package in your own code then it will pull in more.

**Comment by cherniavskii** [comment]
Thanks for your response!
Indeed, in my build rxjs is much smaller, than whole rxjs library.
And thank you a lot for such a great library! ;)

**Comment by jeffbski** [comment]
You are quite welcome! I appreciate the feedback.
