### ISSUE TITLE
Error in Component render is reported by createLogicAction$

### ISSUE THREAD

**Issue by jktravis** [jeffbski/redux-logic#59]
I don't know if this is a problem with `redux-logic`, per se. But I do see these kinds of errors so much that I'm curious is there's something that I should be doing better in order to catch them so they `createLogicAction$` isn't the end of the line for the error. 

![2017-05-19_13-09-49](https://cloud.githubusercontent.com/assets/438688/26258949/db78e5c0-3c94-11e7-9f7d-a7c044eea8f4.jpg)

It's important to note that the error here is happening in my `VirtualizedGrid`'s render function, and as best as I can tell, there are no errors within any dispatched actions. 

I'd like to be able to to bubble up errors like this to the user through a toast. I have code in place for things like that, but it seems that since the "final stop" for these is in `redux-logic`, my other code doesn't have a chance to grab it, 

Have you or anyone else see issues like this?

**Comment by jeffbski** [comment]
@jktravis Thanks for the question, yes the error is coming from elsewhere and redux-logic is simply console logging the error so it isn't lost. It is happening during the actual store.dispatch so that means it could be in the reducer or even in the components that are getting rendered. 

One reason I log it in this situation is so that the error doesn't get lost completely . If the error occurs in the component or in reducer then the whole react pipeline can be broken and thus the app might not be able to show the error through your normal notification mechanism. 

In this particular case the error is coming from the component, so it is likely that you need to somehow check the data coming in or how you are fetching for the cell (accounting for nulls and incomplete objects). Extra unit testing especially for the edge cases would be probably help catch that sort of thing. Also another tip is to use things like `lodash/fp/get` which gracefully handles nulls well when getting a deep property (so you don't have to do lots of checks yourself). 

```js
import get from 'lodash/fp/get';
const obj = { foo: { bar: { baz: 123 }}};
// get obj.foo.bar.baz and if any property is missing just return undefined
const baz = get('foo.bar.baz')(obj); 
```

Hope that helps.

**Comment by jktravis** [comment]
Thanks, @jeffbski. I was really just curious as to why a component-level error was causing `redux-logic` to report the error. I guessing it's simply due to the component being connected to Redux.
