### ISSUE TITLE
Strange initialization problems

### ISSUE THREAD

**Issue by TimMurnaghan** [jeffbski/redux-logic#62]
I haven't yet been able to extract this out into a small enough example so I'll describe the errors to see if it rings a bell with anybody before I spend the effort making a stand-alone example.

 I'm trying to run redux-logic and reducers in node for tests and I'm getting mysterious rxjs internal errors if I run a small-ish test examples - but not if I run a bigger one.

The main error is 
C:\...\node_modules\rxjs\operator\toPromise.js:64
        throw new Error('no Promise impl found');
        ^
Which is caused by calling whenComplete() in the tests

Also if I don't set warnTimeout to 0 in the middleware - then I get:
TypeError: root_1.root.setInterval is not a function
    at AsyncAction.requestAsyncId (C:\...\node_modules\rxjs\src\scheduler\AsyncAction.ts:72:17)

Both of these look like it's incompletely initialized - but I created them with createLogicMiddleware and createLogic.
Is there a trick I've missed about starting something?

This is using redux-logic 0.12.1 (had same Promise problem with earlier) on node 6.10.2 on Windows 7 if that's relevant.

**Comment by jeffbski** [comment]
@TimMurnaghan Thanks for reaching out. We'll see if we can get to the bottom of these problems and resolve. It looks like the environment where you running this does not have a default implementation of Promise. Most browsers and environments already have this built in, but you can polyfill this pretty easily.

If you add `core-js` to your project with `npm add core-js --save` and then include in your source.

```js
import from 'core-js/fn/promise';
// OR require('core-js/fn/promise'); // if using commonjs
```

Then that will include a polyfill for ES6 promises if one is needed.

By only importing/requiring the promise part, we only import that portion of the core-js libary keeping things smaller. 

I'm not sure about the setInterval problem, but maybe it is something similar. 

Just as an idea, you could try importing/requiring all of core-js to see if that resolves all your issues. 

```js
import 'core-js';
// OR require('core-js');
```
If that works then there is something else that needs to be polyfilled in addition to promises and we can look closer to figure out what.

Could you let me know what OS version and what Node.js / browsers you are trying to support, whether you are doing any babel transpiling, and whether the issue is when you are running in browser or node.js?

It might be useful to see your package.json and babel configurations so you could include a link to a gist for those.

**Comment by jeffbski** [comment]
I think I'll also update the docs to include the fact that if one doesn't have a promise implementation and how to include that from core-js.

**Comment by TimMurnaghan** [comment]
@jeffbski Thanks for the thoughts on this. The weird thing is that there is a Promise implementation. I should have mentioned that I am using babel-node so that should be including core  (the rest of the environment was in the original Q - node 6.10 on Windows 7).  It's fine when we use Promises in  the Request calls in the middleware - it's just that rxjs isn't finding it in this case.. If I just change the toPromise() call in whenComplete to toPromise(Promise) without any further includes it works fine. That's why I wondered if it was something about initialization - so maybe you're right about the babel config.

I'll try to reproduce in a reasonably small gist and let you know.

**Comment by TimMurnaghan** [comment]
@jeffbski OK. I've got to the bottom of it. I had to go inside rxjs to see where it got the Promise constructor from. My tests had faked a global window object (for some api origin stuff) which rxjs took to be a real "root" and assumed that it should have the module info.

It's one of those bugs where the symptom and cause are a long way away from each other - made worse by the tricky incompatibilities in the global environments, so not really a redux-logix problem but thanks again for the response.

**Comment by jeffbski** [comment]
@TimMurnaghan thanks for letting us know.

**Comment by sanbornhilland** [comment]
@TimMurnaghan Do you remember what specifically you were faking? I'm running into the same problem even though I have a `Promise` implementation available globally.

**Comment by TimMurnaghan** [comment]
@sanbornhilland Sorry for slow response - but yes it's because of rxjs trying to be slightly too clever and assuming things from seeing global.window. Hopefully between our responses the next person will get enough clues.
