### ISSUE TITLE
How to get notified when async operation is done?

### ISSUE THREAD

**Issue by kruyvanna** [jeffbski/redux-logic#75]
Hi, how to get notified when an async operation is done?

In redux-thunk I can do:

    import {register} from './actions' 
    
    const info = { id: 1, name: 'foo' }
    register(info)
    .then( () => {
      // DONE! => eg. change route
    })

**Comment by jktravis** [comment]
If your register function is returning a Promise, and you are using it inside of a "logic" file, you would just use the function just as you do in your example. 

```javascript
// registerLogic.js
import { register } from './actions' 
import { createLogic } from 'redux-logic'; 

const registerLogic = createLogic({
   type: 'REGISTER',
  
  process() {
    const info = { id: 1, name: 'foo' }
    register(info)
    .then( () => {
      // DONE! => eg. change route
    })
  }
});
```

Does that help? Or perhaps I need more information.

**Comment by jktravis** [comment]
[process-hook](https://github.com/jeffbski/redux-logic/blob/master/docs/api.md#process-hook)

**Comment by kruyvanna** [comment]
hi @jktravis thanks for ur reference, but what I need is calling register() function from the component.

register() is the action creator function. So it doesn't return a promise.

**actions.js**

    export const register = data => ({ type: REGISTER_EMPLOYEE, payload: data })


here is my **logic.js**

    import { createLogic } from 'redux-logic'
    import {
    	REGISTER_EMPLOYEE,
    	CANCEL_REGISTER_EMPLOYEE,
    	REGISTER_EMPLOYEE_SUCCESS,
    	REGISTER_EMPLOYEE_FAILED
    } from './actions'
    import { SERVER_URL } from '../Constants'
    
    const registerEmployeeLogic = createLogic({
    	// declarative built-in functionality wraps your code
    	type: REGISTER_EMPLOYEE, // only apply this logic to this type
    	cancelType: CANCEL_REGISTER_EMPLOYEE, // cancel on this type
    	latest: true, // only take latest
    
    	processOptions: {		
    		dispatchReturn: true, // use returned/resolved value(s) for dispatching		
    		successType: REGISTER_EMPLOYEE_SUCCESS, // dispatch this success act type
    		failType: REGISTER_EMPLOYEE_FAILED // dispatch this failed action type
    	},
    	
    	process({ http, getState, action }) {
    		return http
    			.post(`${SERVER_URL}/api/employees`, action.payload)
    			.then(resp => resp.data)
    	}
    })
    
    export default [registerEmployeeLogic]
    

**component.js**

    import {register} from './acitons'
    
    class NewEmployee extends Component {	
    
    	handleSubmit(info) {		
    		this.props.register(info)
    		// I need to know when register() complete so I can chagne the route
    	}	
    }
    
    const enhance = connect(
      state => ({
      }),
      {
        register    
      }
    );
    
    export default enhance(NewEmployee);    

any idea?

**Comment by jktravis** [comment]
It looks like you've already `connect`ed the component, so, that gives you access to [`dispatch`](http://redux.js.org/docs/api/Store.html#dispatch) on props. (You could also use [`bindActionCreators`](http://redux.js.org/docs/api/bindActionCreators.html)

Since `dispatch` would be on props, from your component you would:

**component.js**
```javascript
	handleSubmit(info) {		
		this.props.dispatch(this.props.register(info))
	}
```

Since you're using Redux, it's probably best to defer any side-effects from this action to the middleware, in this case, it's redux-logic. So, you're process hook might look like:

**logic.js**
```javascript
	process({ http, getState, action }) {
		return http
			.post(`${SERVER_URL}/api/employees`, action.payload)
			.then(resp => {
                                // change route
                                return resp.data;
                         })
	}
```

This will run whatever code you want at the `//change route` line after the server responds.

**Comment by jeffbski** [comment]
Thanks @jktravis for responding with the awesome suggestions. I agree with everything he has said. 

It's just a change in perspective, instead of waiting for things to complete and triggering things in your action creators, you instead just do that in your logic process actions as @jktravis mentioned. Do whatever promise API waiting in there. Sometimes you can also break things up into new actions, so you could listen for the action REGISTER_EMPLOYEE_SUCCESS and then change route there.

If you are using something like react-router-redux then you can also dispatch to cause a route change. So you might use the `process({ http, getState, action}, dispatch, done)` form to make multiple dispatches.

**Comment by kruyvanna** [comment]
@jktravis @jeffbski 
I see. Well explained.
Thanks for the explanation.

**Comment by fgiarritiello** [comment]
Another approach to make the logic function more generic (what if I want to use the same logic but not redirecting to a different url?) is to pass a callback with the action payload:

`process({ http, getState, action }) {
		return http
			.post(`${SERVER_URL}/api/employees`, action.payload)
			.then(resp => {
                                // do not change route here, instead...
                               action.payload.successCB();
                                return resp.data;
                         })
	}`

then in your container:

`handleSubmit(info) {		
		this.props.dispatch(this.props.register(info, () => {
                     // redirect to new url
                 }))
	}`
