### ISSUE TITLE
How to deal with long running processes?

### ISSUE THREAD

**Issue by nripendra** [jeffbski/redux-logic#76]
In applications, there may be very long running processes. I'm confused, if redux-logic can deal with such process?
For example, in a chat client application, once client has been started we may need to check for internet connectivity through out the application's life.
We may be listening to online/idle/offline etc status of friends, which also occurs through out the whole application life.
Is redux-logic correct place to put such logics?

**Comment by jeffbski** [comment]
Yes, since you can listen to an observable then it can continue to get notifications as long as you want. 

We can make the observable automatically reconnect if the ws drops. 

Here's an example https://jsfiddle.net/jeffbski/baqz3rkj/

I created a reconnecting websocket client that also indicates when it is connected so that can be monitored too. So in the logic file we simply connect to it and handle received messages.

**Comment by DimitryDushkin** [comment]
To deal with stream of actions of certain type you should create Observable outside of `createLogic` and execute `.next(action)` in `validate || process || etc.` section?.  There is no built-in stream of actions (like in redux-observable). Is this correct?

**Comment by jeffbski** [comment]
Currently that is true, but I've been thinking about this feature and am planning to add the capability so that you can have access to the stream inside of your process hook. I'm going to discuss with some other users this week at Connect.tech and will work on getting it in there. I'm thinking it will just be exposed as another dep, maybe named `action$` unless we come up with a better name.

**Comment by jeffbski** [comment]
I've added action$ (stream of actions in v2) so you can listen for actions and operate on the stream now. 

I have some examples:

 - drag and drop - https://codesandbox.io/s/n34x5j3jv4
 - websockets - https://codesandbox.io/s/m38l7n745y
