### ISSUE TITLE
Multi step transform example

### ISSUE THREAD

**Issue by scriptjs** [jeffbski/redux-logic#80]
I've not yet located a transform example that consists of multiple steps. Is there an example available? Thank you.

**Comment by ugility** [comment]
Not sure why the "insert code" option doesn't like the code... Only part seems to format correctly when previewing. 

So you might need to copy/paste it into your editor if it isn't clear:

`const myLogic = createLogic({
    type: 'INIT',
    debounce: 1000,
    transform({ getState, action, cancelled$, deps }, next, reject) {
      // EXAMPLE 1:
      const transform1$ = Observable.of(action)
        .map(action => {
          // do calculations, return transformed action, or make it a mergeMap and
          // return an Observable that emits the transformed action
        })
        .mergeMap(action => {
          // more transformations, async example
          return Observable.of(action)
            .map(action => action)
        })

      const transform2$ = transform1$
        .map(action => {
          // do more stuff, or mergeMap and return an Observable that emits the transformed action

        })

      return transform2$
        .map(action => next(action)); // signal next()

      // EXAMPLE 2:

      return Observable.create(observer => {
        transform1$.subscribe((action) => {
          // side effects...
          
          // then..
          observer.next(action); // ...or another observable/subscription.
        });
      })
        .map(action => {
          // more side effects...

          // finally...
          next(action);
        })
    }
  });`

**Comment by jeffbski** [comment]
@scriptjs thanks for the question and thanks @ugility for responding with a nice detailed answer. 

About the only clarification I might make is that the transform step is expecting next (or reject) to be called exactly once. So while process hook can dispatch multiple times the intercept hook (transform/validate) only can call next/reject once. 

However the example above is still valid if you are doing multiple things to be able to do that single next call.

If you need to dispatch multiple times then I'd recommend using the process hook instead. 

Alternatively you could get sneaky and add your store.dispatch method as a dep and be able to dispatch multiple times however doing things that way, those dispatches would not be governed by redux-logic cancellation since you would be calling store.dispatch directly. 

Here's an example of how you could give your store.dispatch as a dep.

```js
const logicMiddleware = createLogicMiddleware(logic, deps);
const store = createStore(reducer, applyMiddleware(logicMiddleware);
const additionalDeps = {
  storeDispatch: store.dispatch   // providing a way to dispatch directly
};
logicMiddleware.addDeps(additionalDeps);
```

Then you would have an additional dependency injected called storeDispatch which you could call anywhere in your hooks to dispatch any number of times, but remember that these are outside of the control of redux-logic cancellation.

**Comment by scriptjs** [comment]
@ugility @jeffbski  Thank you for these detailed answers and for the library.  I think I need to explore a bit further. From what I have gathered thus far, transform is a alias of validate. I think perhaps it needs to grow a transform method that is not an alias to handle a sequence of methods in a way that could be handled in series or parallel. That is for me what is missing at this point.

**Comment by ugility** [comment]
@scriptjs could you maybe provide an example of what you mean? I'm not saying a disagree with you, because I've actually modified the library to do exactly what you're proposing. But it's for a completely different reason than what I think you're trying to describe. So if you could post an example it'd help me better understand what you're envisioning, and maybe some of the mods I've made to the library could help

**Comment by scriptjs** [comment]
@ugility What I am looking for is analogous to piping transformations using a node stream.
