### ISSUE TITLE
Order of logics in array

### ISSUE THREAD

**Issue by artificis** [jeffbski/redux-logic#82]
For most asynchronous (mostly api calls) handlings, we need to show sort of loading indicator (or spinner) UI element. Since these are pretty common in every api call logic, I tried the following:

`constants.js`
```js
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN/ASYNC';
```

`logics.js`
```js
import { createLogic, createLogicMiddleware } from 'redux-logic';
import { setWipFlag, clearWipFlag } from './actionCreators';
import { GET_ACCESS_TOKEN } from './constants';

const setWipFlagLogic = createLogic({
  type: /\/ASYNC$/,
  process({ getState, action }, dispatch, done) {
    console.log('set');
    dispatch(setWipFlag());
    done();
  }
});

const loginLogic = createLogic({
  type: GET_ACCESS_TOKEN,
  async process({ getState, action: { payload } }, dispatch, done) {
    console.log('login');
  }
});

const clearWipFlagLogic = createLogic({
  type: /\/ASYNC$/,
  process({ getState, action }, dispatch, done) {
    console.log('clear');
    dispatch(clearWipFlag());
    done();
  }
});

createLogicMiddleware([
  setWipFlagLogic,
  loginLogic,
  clearWipFlagLogic
]);

```

I expected to see the following in my console:
```
set
login
clear
```

Instead, what I actually saw was:
```
clear
login
set
```

So is taking individual logic from array is quite random or does it work FILO like stack?
If it works FILO way, why don't we explicitly specify about this in the api documentation?

**Comment by jeffbski** [comment]
Thanks for raising the question @clthck. Your original assumptions are correct in that the messages pass down the logic stack in the order they are listed in the array. I will test your code myself to see what happens, though like you I would have expected to see set, login, clear. 

I believe that I already have tests that verify things like that using the monitor$ which helps see the inner workings of exactly what is happening. 

One more point I would mention is that even though the order of logic is the order they are given actions, in most cases, these types of things are not instantaneous, so the spinner would display, then the login would take a few second and then the clear would fire. So order is usually less important since these actions are staggered typically. However it is the intent that earlier logic should get the action before the later action. I would expect that to be true on both the intercept (validate/transform) side and via the process. 

Another question, are you using the latest version of redux-logic? I do remember taking out an extra pause that was being added after the intercept before running the process, but I removed that a little while back. I don't believe there is any extra artificial delay in the current version. If there was any sort of delay for the process step then that could have accounted for what you were seeing.

**Comment by clthck** [comment]
Actually I'm more up to what would be the best way to DRY this common stuff for showing loading indicator UI, using redux-logic.
For now, I have to import two action creators (`setWipFlag`, `clearWipFlag`), wrap the process logic with dispatching these two actions. What is your thought?

**Comment by jeffbski** [comment]
Sure. I think the approach that many people take would be to use a consistent naming convention in your actions and that way you can use a regex similar to what you were doing except that you would typically use like a leading or trailing 'ASYNC' for the setSpinner logic and then for the clearSpinnerLogic regex for /(_SUCCESS|_FAILURE)$/ to catch the completion or failure.

**Comment by scriptjs** [comment]
@jeffbski What was your result for the above with the current code?

**Comment by artificis** [comment]
Alright, I ended up writing like this: https://github.com/knocknock-team/react-app-suspenders
And I'm pretty much happy with this solution 🙂
