### ISSUE TITLE
Access original logic action payload parameters on cancellation?

### ISSUE THREAD

**Issue by therealgilles** [jeffbski/redux-logic#96]
Question: If I have an action that has some payload parameters, how can I access those parameters in the cancellation action when it is triggered?

```
const myLogic = createLogic({
  type: MY_ACTION,
  cancelType: CANCEL_MY_ACTION,
  ...
```

Is the solution/workaround to use cancelled$.subscribe() and dispatch another action with the parameters like this?

```
process({ httpClient, getState, action }, dispatch, done) {
  const params = action.payload
  cancelled$.subscribe(() => {
      dispatch(cancel_my_action_with_params(params));
    });
  ...
```

**Comment by jeffbski** [comment]
That's a good question. Since these actions are independent then they don't have access to each others payload. 

You could do something like you indicated using the cancelled$ to know when it cancels and then dispatch another action with the data like you suggested. However since the observable is in the process of cancelling, the dispatch might not go out. I'd have to test it to know the timing of whether the cancellation has already stopped the dispatch or not. 

If it is not dispatching then you might have to get access to your store and use it's dispatch to send it out directly. So you would need to export your store from somewhere and import it here, or after you use logicMiddlware to create your store, then you can turn around and add an additional dep that will be injected, like 

```js
// I have created logicMiddleware and used to create my store
// now I can add a new dep
logicMiddleware.addDeps({
  storeDispatch: store.dispatch // bypasses any cancellation
});
```

```js
process({ httpClient, getState, action, storeDispatch }, dispatch, done) {
  const params = action.payload
  cancelled$.subscribe(() => {
      storeDispatch(cancel_my_action_with_params(params));
    });
  ...
```

**Comment by therealgilles** [comment]
It seems to work without having to pass store.dispatch through middleware.
